import type {Metadata} from "next";

import "./globals.css";
import {Lato} from "next/font/google";
import {ClerkProvider} from "@clerk/nextjs";

const inter = Lato({weight: ["100", "300", "400", "700", "900"]});

export const metadata: Metadata = {
  title: "Manage Travels",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
